CXX = g++
CXXFLAGS = -g -Wall
LDFLAGS = -L. -lgterm -L/usr/X11R6/lib -lX11
bindir = /usr/local/bin
DESTDIR =
BIN_OWNER = root
BIN_GROUP = wheel
BIN_MODE = 555

PTY_CODE = classic
# valid settings for PTY_CODE:
#    openpty (BSD, Linux with glibc)
#    unix98 (Linux)
#    classic (every UNIX (?), should be SUID root)

CPPFLAGS = -I/usr/X11R6/include
# other flags: -DUSE_UTMP for utmp logging (needs (?) SUID root)
#   warning: doesn't work on FreeBSD for now
